services:
  api:
    container_name: expense_api
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - ../backend/.env.docker
    depends_on:
      - postgres
      - redis
    volumes:
      - ../backend:/app:delegated
      - /app/node_modules
    command: npm run dev

  worker:
    container_name: expense_worker
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env.docker
    depends_on:
      - redis
    volumes:
      - ../backend:/app:delegated
      - /app/node_modules
    command: npm run worker

  postgres:
    image: postgres:14
    container_name: expense_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: expense_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: